trigger:
- master

pool:
  name: Default

steps:
- checkout: self

- script: python --version
  displayName: 'Show Python version'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: python -m unittest discover
  displayName: 'Run tests'